language: android  # this means the project will be built in an Android environment
jdk: oraclejdk8

android:
  components:
    - tools               # will use latest version of Android SDK tools
    - platform-tools      # as above
    - build-tools-25.0.2  # buildToolsVersion
    - android-25          # compileSdkVersion
