sudo: false

language: android  # this means the project will be built in an Android environment

android:
  components:
    - tools               # will use latest version of Android SDK tools
    - tools               # Apparently declaring twice fixes a Travis bug - the group project is run by the tools!
    - platform-tools
    - build-tools-25.0.2  # buildToolsVersion
    - android-25          # compileSdkVersion
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-25 # Let's run in a suitable emulator

jdk:
  - oraclejdk8

script:
  - ./gradlew test
